if(CMAKE_C_COMPILER_ID MATCHES GNU)
  include(${CMAKE_CURRENT_LIST_DIR}/GNU/C.cmake)
elseif(CMAKE_C_COMPILER_ID MATCHES Intel)
  include(${CMAKE_CURRENT_LIST_DIR}/Intel/C.cmake)
elseif(CMAKE_C_COMPILER_ID MATCHES Clang)
  include(${CMAKE_CURRENT_LIST_DIR}/Clang/C.make)
else()
  message(WARNING "C compiler ${CMAKE_C_COMPILER} never tested")
endif()
