macro(write_to_cloc_list list_of_sources)
    get_filename_component(lib ${CMAKE_CURRENT_SOURCE_DIR} NAME)
    if(EXISTS "${CMAKE_BINARY_DIR}/cloc/cloc_list-${lib}")
        file(REMOVE ${CMAKE_BINARY_DIR}/cloc/cloc_list-${lib})
    endif()
    foreach(source ${list_of_sources})
        file(APPEND ${CMAKE_BINARY_DIR}/cloc/cloc_list-${lib} "${CMAKE_CURRENT_SOURCE_DIR}/${source}\n")
    endforeach()
endmacro()
