# frozen_string_literal: true
source "https://rubygems.org"

gem "danger"
gem "danger-commit_lint"
gem "danger-lgtm"
# gem 'danger-code_style_validation', '0.3.0' , :git => 'https://github.com/flix-tech/danger-code_style_validation.git'
gem 'danger-code_style_validation', :git => 'https://github.com/robertodr/danger-code_style_validation.git', :branch => 'style-flag'
