CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
C  codata.h revised 2006/06/24 with 2002 CODATA recommended values.
C  From
C    Reviews of Modern Physics 77, 1-107 (2005)
CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
C  to be updated at next release of DALTON
CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
C
C  codata.h revised 1999/04/29 and combined with units.h 
C
C  From
C  "CODATA Recommended Values of the Fundamental Physical Constants: 1998"
C                     Peter J. Mohr and Barry N. Taylor
C  Journal of Physical and Chemical Reference Data, Vol. 28, No. 6, 1999
C
C -- Fundamental constants, atomic units, Avogadro's constant
#if defined (SYS_CRAY)
CX
CX Codata 2002
CX    REAL XAMU, XAU
CX
      REAL CVEL, ALPHAC, ALPHA2
      REAL XTANG,XFAMU,ECHARGE,HBAR,XFMOL
      REAL XTJ,XTKAYS,XTHZ,XTEV,XKJMOL,XKCMOL,XTKJML,
     &     XTKCML,XTNM,XAJOUL,XTANGM10,XPRTMAS 
      REAL XFSEC,XTKMML,TESLA,AUTK,DEBYE,DIPSI,PMASS,EMASS,CCM
      REAL FPEPS0, DIPSI
#else
CX
CX Codata 2002
CX    DOUBLE PRECISION XAMU, XAU
CX
      DOUBLE PRECISION CVEL, ALPHAC, ALPHA2
      DOUBLE PRECISION XTANG,XFAMU,ECHARGE,HBAR,XFMOL
      DOUBLE PRECISION XTJ,XTKAYS,XTHZ,XTEV,XKJMOL,XKCMOL,XTKJML,
     &                 XTKCML,XTNM,XAJOUL,XTANGM10,XPRTMAS
      DOUBLE PRECISION XFSEC,XTKMML,TESLA,AUTK,DEBYE,DIPSI,
     &                 PMASS,EMASS,CCM
      DOUBLE PRECISION FPEPS0 
#endif
#include <pcm_pi.h>
C
CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
CX codata 2002
CXnew PARAMETER ( XAMU = 9.109 382 6 D-31, XAU = 1.660 538 86 D-27)
CXnew PARAMATER ( XFAMU  = XAU / XAMU
CX new value corresponds to 1822.8884796D0 (ie no change with 10 sig fig)
CXold PARAMATER ( XFAMU  = 1822.88848 D0)
CX    PARAMETER ( XTANG = 0.529 177 2108 D0) 
CX    PARAMETER ( XTANGM10 = XTANG*1.0D-10)
CX    PARAMETER ( ECHARGE = 1.602 176 53 D-19)
CX    PARAMETER ( HBAR = 1.054 571 68 D-34)
CX    PARAMETER ( XFMOL = 6.022 141 5 D23 )
CX    PARAMETER ( PMASS = 1.007 276 466 88 D0)
CX    PARAMETER ( EMASS = 9.109 382 6 D-31)
CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
C
      PARAMETER ( XTANG = 0.529 177 2083 D0, XFAMU  = 1822.88848 D0,
     &            ECHARGE = 1.602 176 462D-19, HBAR = 1.054 571 596D-34)
      PARAMETER ( XFMOL = 6.022 141 99 D23 )
      PARAMETER ( XTANGM10 = XTANG*1.0D-10)
C
      PARAMETER ( PMASS = 1.007276470D0, EMASS = 9.10938188D-31)
C
#include <pcm_alphac.h>
C -- 4*pi*epsilon0
      PARAMETER ( FPEPS0 = 1.0D7/(CCM**2) )
C -- conversion from hartree (au) to:
      PARAMETER ( XTJ  = HBAR**2/(XTANGM10*XTANGM10*EMASS),
     &            XTHZ =  HBAR/(2.0D0*PI*XTANGM10*XTANGM10*EMASS),
     &            XTKAYS = 1.0D-2*XTHZ/CCM,
     &            XTEV = XTJ/ECHARGE,
     &            XKJMOL = XTJ*XFMOL*1.D-3, XKCMOL = XKJMOL/4.184 D0,
     &            XTKJML = XKJMOL,          XTKCML = XKCMOL,
     &            XTNM = 1.D7/XTKAYS,       XAJOUL = 1.0 D18*XTJ)
C
C -- other
CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
CX codata 2002
CX    PARAMETER ( XFSEC = HBAR/XTJ)
CX    PARAMETER ( XTKMML = 974.864 D0)
CX    PARAMETER ( TESLA=(XTANG*XTANG*ECHARGE/HBAR)*1.D-20 )
CX    PARAMETER ( AUTK = 3.157 7465 D5 )
CX    PARAMETER ( DEBYE = ECHARGE*XTANG*CCM*1.D11 )
CX    PARAMETER ( XPRTMAS = 1836.152 672 61 D0 )   
CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      PARAMETER ( XFSEC = HBAR/XTJ)
      PARAMETER ( XTKMML = 974.864 D0)
      PARAMETER ( TESLA=(XTANG*XTANG*ECHARGE/HBAR)*1.D-20 )
      PARAMETER ( AUTK = 3.157 7465 D5 )
      PARAMETER ( DEBYE = ECHARGE*XTANG*CCM*1.D11 )
      PARAMETER ( DIPSI = ECHARGE*XTANGM10*1.0D+30 )
      PARAMETER ( XPRTMAS = 1836.152 6675 D0 )   
C
