!     FILE: orgcom.h
      LOGICAL FMMORI
      REAL*8 CMXYZ, ORIGIN, DIPORG, GAGORG, CAVORG, TOTMAS, TNUCMAS
      COMMON /PCM_ORGCOM/ TOTMAS, TNUCMAS, CMXYZ(3), ORIGIN(3),      & 
          DIPORG(3), GAGORG(3), CAVORG(3), FMMORI
