!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!  codata.h revised 2006/06/24 with 2002 CODATA recommended values.
!  From
!    Reviews of Modern Physics 77, 1-107 (2005)
!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!  to be updated at next release of DALTON
!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!
!  codata.h revised 1999/04/29 and combined with units.h 
!
!  From
!  "CODATA Recommended Values of the Fundamental Physical Constants: 1998"
!                     Peter J. Mohr and Barry N. Taylor
!  Journal of Physical and Chemical Reference Data, Vol. 28, No. 6, 1999
!
! -- Fundamental constants, atomic units, Avogadro's constant
#if defined (SYS_CRAY)
!X
!X Codata 2002
!X    REAL XAMU, XAU
!X
      REAL CVEL, ALPHAC, ALPHA2
      REAL XTANG,XFAMU,ECHARGE,HBAR,XFMOL
      REAL XTJ,XTKAYS,XTHZ,XTEV,XKJMOL,XKCMOL,XTKJML,              &
          XTKCML,XTNM,XAJOUL,XTANGM10,XPRTMAS 
      REAL XFSEC,XTKMML,TESLA,AUTK,DEBYE,DIPSI,PMASS,EMASS,CCM
      REAL FPEPS0, DIPSI
#else
!X
!X Codata 2002
!X    DOUBLE PRECISION XAMU, XAU
!X
      DOUBLE PRECISION CVEL, ALPHAC, ALPHA2
      DOUBLE PRECISION XTANG,XFAMU,ECHARGE,HBAR,XFMOL
      DOUBLE PRECISION XTJ,XTKAYS,XTHZ,XTEV,XKJMOL,XKCMOL,XTKJML,  &
                      XTKCML,XTNM,XAJOUL,XTANGM10,XPRTMAS
      DOUBLE PRECISION XFSEC,XTKMML,TESLA,AUTK,DEBYE,DIPSI,        &  
                      PMASS,EMASS,CCM
      DOUBLE PRECISION FPEPS0 
#endif
#include <pcm_pi.h>
!
!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!X codata 2002
!Xnew PARAMETER ( XAMU = 9.1093826D-31, XAU = 1.66053886D-27)
!Xnew PARAMATER ( XFAMU  = XAU / XAMU
!X new value corresponds to 1822.8884796D0 (ie no change with 10 sig fig)
!Xold PARAMATER ( XFAMU  = 1822.88848D0)
!X    PARAMETER ( XTANG = 0.5291772108D0) 
!X    PARAMETER ( XTANGM10 = XTANG*1.0D-10)
!X    PARAMETER ( ECHARGE = 1.60217653D-19)
!X    PARAMETER ( HBAR = 1.05457168D-34)
!X    PARAMETER ( XFMOL = 6.0221415D23 )
!X    PARAMETER ( PMASS = 1.00727646688D0)
!X    PARAMETER ( EMASS = 9.1093826D-31)
!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!
      PARAMETER ( XTANG = 0.5291772083D0, XFAMU  = 1822.88848D0,    &
                 ECHARGE = 1.602176462D-19, HBAR = 1.054571596D-34)
      PARAMETER ( XFMOL = 6.02214199D23 )
      PARAMETER ( XTANGM10 = XTANG*1.0D-10)
!
      PARAMETER ( PMASS = 1.007276470D0, EMASS = 9.10938188D-31)
!
#include <pcm_alphac.h>
! -- 4*pi*epsilon0
      PARAMETER ( FPEPS0 = 1.0D7/(CCM**2) )
! -- conversion from hartree (au) to:
      PARAMETER ( XTJ  = HBAR**2/(XTANGM10*XTANGM10*EMASS),                   &
                 XTHZ =  HBAR/(2.0D0*PI*XTANGM10*XTANGM10*EMASS),             &
                 XTKAYS = 1.0D-2*XTHZ/CCM,                                    &
                 XTEV = XTJ/ECHARGE,                                          &
                 XKJMOL = XTJ*XFMOL*1.D-3, XKCMOL = XKJMOL/4.184D0,          &
                 XTKJML = XKJMOL,          XTKCML = XKCMOL,                   &
                 XTNM = 1.D7/XTKAYS,       XAJOUL = 1.0D18*XTJ)
!
! -- other
!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!X codata 2002
!X    PARAMETER ( XFSEC = HBAR/XTJ)
!X    PARAMETER ( XTKMML = 974.864D0)
!X    PARAMETER ( TESLA=(XTANG*XTANG*ECHARGE/HBAR)*1.D-20 )
!X    PARAMETER ( AUTK = 3.1577465D5 )
!X    PARAMETER ( DEBYE = ECHARGE*XTANG*CCM*1.D11 )
!X    PARAMETER ( XPRTMAS = 1836.15267261D0 )   
!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      PARAMETER ( XFSEC = HBAR/XTJ)
      PARAMETER ( XTKMML = 974.864D0)
      PARAMETER ( TESLA=(XTANG*XTANG*ECHARGE/HBAR)*1.D-20 )
      PARAMETER ( AUTK = 3.1577465D5 )
      PARAMETER ( DEBYE = ECHARGE*XTANG*CCM*1.D11 )
      PARAMETER ( DIPSI = ECHARGE*XTANGM10*1.0D+30 )
      PARAMETER ( XPRTMAS = 1836.1526675D0 )   
!
