if (NOT DEFINED DEFAULT_C_FLAGS_SET OR RESET_FLAGS)

  if(CMAKE_C_COMPILER_ID MATCHES GNU)
	  set(CMAKE_C_FLAGS         "-Wall -Wextra -Winit-self -Wuninitialized -Wmissing-declarations -Wwrite-strings -std=c99 -DRESTRICT=restrict -DFUNDERSCORE=1 -fPIC")
	  set(CMAKE_C_FLAGS_DEBUG   "-O0 -g3 -Wall")
	  set(CMAKE_C_FLAGS_RELEASE "-O3")
          if(ENABLE_VECTORIZATION)                                                    
		  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${C_ARCHITECTURE_FLAGS} ${DEFINITIONS}")
          endif()	      
          if(ENABLE_CODE_COVERAGE)                                                             
		  set(CMAKE_C_FLAGS      "${CMAKE_C_FLAGS} -fprofile-arcs -ftest-coverage")
	          set(CMAKE_C_LINK_FLAGS "-fprofile-arcs -ftest-coverage")
          endif()
  endif()
  
  if(CMAKE_C_COMPILER_ID MATCHES Intel)
          set(CMAKE_C_FLAGS         "-Wall -Wuninitialized -restrict -DRESTRICT=restrict -vec-report0 -std=c99 -fPIC") 
          set(CMAKE_C_FLAGS_DEBUG   "-O0 -g -w3 -vec-report")
          set(CMAKE_C_FLAGS_RELEASE "-O3 -ip")
          set(CMAKE_C_LINK_FLAGS    "-shared-intel -fPIC")
          if(ENABLE_VECTORIZATION)                                                    
		  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${C_ARCHITECTURE_FLAGS} ${DEFINITIONS}")
          endif()	      
  endif()
  
  if(CMAKE_C_COMPILER_ID MATCHES PGI)
	  set(CMAKE_C_FLAGS         "${CMAKE_C_FLAGS}")
	  set(CMAKE_C_FLAGS_DEBUG   "${CMAKE_C_FLAGS_DEBUG} -g -O0")
	  set(CMAKE_C_FLAGS_RELEASE "${CMAKE_CFLAGS_RELEASE} -O3 -fast -Munroll -Mvect=idiom -c9x -DRESTRICT=restrict")
  endif()
  
  if(CMAKE_C_COMPILER_ID MATCHES XL)
	  set(CMAKE_C_FLAGS         "${CMAKE_C_FLAGS} -qcpluscmt")
	  set(CMAKE_C_FLAGS_DEBUG   "${CMAKE_C_FLAGS_DEBUG} ")
	  set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3")
  endif()
  
  if(CMAKE_C_COMPILER_ID MATCHES Clang)
	  set(CMAKE_C_FLAGS         "-Wall -Wextra -Winit-self -Wuninitialized -Wmissing-declarations -Wwrite-strings -std=c99 -DRESTRICT=restrict -DFUNDERSCORE=1 -fPIC")
	  set(CMAKE_C_FLAGS_DEBUG   "-O0 -g3 -Wall")
	  set(CMAKE_C_FLAGS_RELEASE "-O3")
          if(ENABLE_VECTORIZATION)                                                    
		  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${C_ARCHITECTURE_FLAGS} ${DEFINITIONS}")
          endif()	      
  endif()

  save_compiler_flags(C)

endif()
