include(SaveCompilerFlags)
include(OptimizeForArchitecture)

if(ENABLE_VECTORIZATION)
	set(CXX_ARCHITECTURE_FLAGS)
	set(C_ARCHITECTURE_FLAGS)
	set(Fortran_ARCHITECTURE_FLAGS)
	OptimizeForArchitecture()
	message(STATUS "Vectorization flags used:")
	message(STATUS "  CXX: ${CXX_ARCHITECTURE_FLAGS}")
	message(STATUS "  C: ${C_ARCHITECTURE_FLAGS}")
	message(STATUS "  Fortran: ${Fortran_ARCHITECTURE_FLAGS}")
endif()	

if(CMAKE_C_COMPILER_WORKS)
    include(CFlags)
endif()

if(CMAKE_CXX_COMPILER_WORKS)
    include(CXXFlags)
endif()

if(CMAKE_Fortran_COMPILER_WORKS)
    include(FortranFlags)
endif()
