#define BOOST_TEST_MODULE GePolCavity

#include <boost/test/unit_test.hpp>
#include <boost/test/floating_point_comparison.hpp>

#include <vector>
#include <cmath>

#include "Config.hpp"

#include "EigenPimpl.hpp"

#include <boost/filesystem.hpp>

#include "GePolCavity.hpp"
#include "PhysicalConstants.hpp"
#include "Symmetry.hpp"

namespace fs = boost::filesystem;

struct GePolCavityC1Test {
    GePolCavity cavity;
    GePolCavityC1Test() {  SetUp(); }
    void SetUp() {
        Eigen::Vector3d origin(0.0, 0.0, 0.0);
        std::vector<Sphere> spheres;
        Sphere sph1(origin,  1.0);
        spheres.push_back(sph1);
        double area = 0.4;
        double probeRadius = 0.0;
        double minRadius = 100.0;
        // C1
        Symmetry group = buildGroup(0, 0, 0, 0);
        cavity = GePolCavity(spheres, area, probeRadius, minRadius, group);
        fs::rename("PEDRA.OUT", "PEDRA.OUT.c1");
        fs::rename("cavity.off", "cavity.off.c1");
    }
};

BOOST_FIXTURE_TEST_SUITE(GePolCavityC1, GePolCavityC1Test)

/*! \class GePolCavity
 *  \test \b GePolCavityC1Test_size tests GePol cavity size for a point charge in C1 symmetry with added spheres
 */
BOOST_FIXTURE_TEST_CASE(size, GePolCavityC1Test)
{
    int size = 32;
    int actualSize = cavity.size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityC1Test_irreducible_size tests GePol cavity irreducible size for a point charge in C1 symmetry with added spheres
 */
BOOST_FIXTURE_TEST_CASE(irreducible_size, GePolCavityC1Test)
{
    int size = 32;
    int actualSize = cavity.irreducible_size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityC1Test_area tests GePol cavity surface area for a point charge in C1 symmetry with added spheres
 */
BOOST_FIXTURE_TEST_CASE(area, GePolCavityC1Test)
{
    double area = 4.0 * M_PI * pow(1.0, 2);
    double actualArea = cavity.elementArea().sum();
    BOOST_REQUIRE_CLOSE(area, actualArea, 1.0e-12);
}

/*! \class GePolCavity
 *  \test \b GePolCavityC1Test_volume tests GePol cavity volume for a point charge in C1 symmetry with added spheres
 */
BOOST_FIXTURE_TEST_CASE(volume, GePolCavityC1Test)
{
    double volume = 4.0 * M_PI * pow(1.0, 3) / 3.0;
    Eigen::Matrix3Xd elementCenter = cavity.elementCenter();
    Eigen::Matrix3Xd elementNormal = cavity.elementNormal();
    double actualVolume = 0;
    for ( int i = 0; i < cavity.size(); ++i ) {
        actualVolume += cavity.elementArea(i) * elementCenter.col(i).dot(elementNormal.col(
                            i));
    }
    actualVolume /= 3;
    BOOST_REQUIRE_CLOSE(volume, actualVolume, 1.0e-12);
}

BOOST_AUTO_TEST_SUITE_END()

struct GePolCavityCsTest {
    GePolCavity cavity;
    GePolCavityCsTest() { SetUp(); }
    void SetUp() {
        Eigen::Vector3d origin(0.0, 0.0, 0.0);
        std::vector<Sphere> spheres;
        Sphere sph1(origin,  1.0);
        spheres.push_back(sph1);
        double area = 0.4;
        double probeRadius = 0.0;
        double minRadius = 100.0;
        // Cs as generated by Oyz
        Symmetry group = buildGroup(1, 1, 0, 0);
        cavity = GePolCavity(spheres, area, probeRadius, minRadius, group);
        fs::rename("PEDRA.OUT", "PEDRA.OUT.cs");
        fs::rename("cavity.off", "cavity.off.cs");
    }
};

BOOST_FIXTURE_TEST_SUITE(GePolCavityCs, GePolCavityCsTest)

/*! \class GePolCavity
 *  \test \b GePolCavityCsTest_size tests GePol cavity size for a point charge in Cs symmetry with added spheres
 */
BOOST_FIXTURE_TEST_CASE(size, GePolCavityCsTest)
{
    int size = 32;
    int actualSize = cavity.size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityCsTest_irreducible_size tests GePol cavity irreducible size for a point charge in Cs symmetry
 */
BOOST_FIXTURE_TEST_CASE(irreducible_size, GePolCavityCsTest)
{
    int size = 16;
    int actualSize = cavity.irreducible_size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityCsTest_area tests GePol cavity surface area for a point charge in Cs symmetry
 */
BOOST_FIXTURE_TEST_CASE(area, GePolCavityCsTest)
{
    double area = 4.0 * M_PI * pow(1.0, 2);
    double actualArea = cavity.elementArea().sum();
    BOOST_REQUIRE_CLOSE(area, actualArea, 1.0e-12);
}

/*! \class GePolCavity
 *  \test \b GePolCavityCsTest_volume tests GePol cavity volume for a point charge in Cs symmetry
 */
BOOST_FIXTURE_TEST_CASE(volume, GePolCavityCsTest)
{
    double volume = 4.0 * M_PI * pow(1.0, 3) / 3.0;
    Eigen::Matrix3Xd elementCenter = cavity.elementCenter();
    Eigen::Matrix3Xd elementNormal = cavity.elementNormal();
    double actualVolume = 0;
    for ( int i = 0; i < cavity.size(); ++i ) {
        actualVolume += cavity.elementArea(i) * elementCenter.col(i).dot(elementNormal.col(
                            i));
    }
    actualVolume /= 3;
    BOOST_REQUIRE_CLOSE(volume, actualVolume, 1.0e-12);
}

BOOST_AUTO_TEST_SUITE_END()

struct GePolCavityC2Test {
    GePolCavity cavity;
    GePolCavityC2Test() { SetUp(); }
    void SetUp() {
        Eigen::Vector3d origin(0.0, 0.0, 0.0);
        std::vector<Sphere> spheres;
        Sphere sph1(origin,  1.0);
        spheres.push_back(sph1);
        double area = 0.4;
        double probeRadius = 0.0;
        double minRadius = 100.0;
        // C2 as generated by C2z
        Symmetry group = buildGroup(1, 3, 0, 0);
        cavity = GePolCavity(spheres, area, probeRadius, minRadius, group);
        fs::rename("PEDRA.OUT", "PEDRA.OUT.c2");
        fs::rename("cavity.off", "cavity.off.c2");
    }
};

BOOST_FIXTURE_TEST_SUITE(GePolCavityC2, GePolCavityC2Test)

/*! \class GePolCavity
 *  \test \b GePolCavityC2Test_size tests GePol cavity size for a point charge in C2 symmetry
 */
BOOST_FIXTURE_TEST_CASE(size, GePolCavityC2Test)
{
    int size = 32;
    int actualSize = cavity.size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityC2Test_irreducible_size tests GePol cavity irreducible size for a point charge in C2 symmetry
 */
BOOST_FIXTURE_TEST_CASE(irreducible_size, GePolCavityC2Test)
{
    int size = 16;
    int actualSize = cavity.irreducible_size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityC2Test_area tests GePol cavity surface area for a point charge in C2 symmetry
 */
BOOST_FIXTURE_TEST_CASE(area, GePolCavityC2Test)
{
    double area = 4.0 * M_PI * pow(1.0, 2);
    double actualArea = cavity.elementArea().sum();
    BOOST_REQUIRE_CLOSE(area, actualArea, 1.0e-12);
}

/*! \class GePolCavity
 *  \test \b GePolCavityC2Test_volume tests GePol cavity volume for a point charge in C2 symmetry
 */
BOOST_FIXTURE_TEST_CASE(volume, GePolCavityC2Test)
{
    double volume = 4.0 * M_PI * pow(1.0, 3) / 3.0;
    Eigen::Matrix3Xd elementCenter = cavity.elementCenter();
    Eigen::Matrix3Xd elementNormal = cavity.elementNormal();
    double actualVolume = 0;
    for ( int i = 0; i < cavity.size(); ++i ) {
        actualVolume += cavity.elementArea(i) * elementCenter.col(i).dot(elementNormal.col(
                            i));
    }
    actualVolume /= 3;
    BOOST_REQUIRE_CLOSE(volume, actualVolume, 1.0e-12);
}

BOOST_AUTO_TEST_SUITE_END()

struct GePolCavityCiTest {
    GePolCavity cavity;
    GePolCavityCiTest() { SetUp(); }
    void SetUp() {
        Eigen::Vector3d origin(0.0, 0.0, 0.0);
        std::vector<Sphere> spheres;
        Sphere sph1(origin,  1.0);
        spheres.push_back(sph1);
        double area = 0.4;
        double probeRadius = 0.0;
        double minRadius = 100.0;
        // Ci as generated by i
        Symmetry group = buildGroup(1, 7, 0, 0);
        cavity = GePolCavity(spheres, area, probeRadius, minRadius, group);
        fs::rename("PEDRA.OUT", "PEDRA.OUT.ci");
        fs::rename("cavity.off", "cavity.off.ci");
    }
};

BOOST_FIXTURE_TEST_SUITE(GePolCavityCi, GePolCavityCiTest)

/*! \class GePolCavity
 *  \test \b GePolCavityCiTest_size tests GePol cavity size for a point charge in Ci symmetry
 */
BOOST_FIXTURE_TEST_CASE(size, GePolCavityCiTest)
{
    int size = 32;
    int actualSize = cavity.size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityCiTest_irreducible_size tests GePol cavity irreducible size for a point charge in Ci symmetry
 */
BOOST_FIXTURE_TEST_CASE(irreducible_size, GePolCavityCiTest)
{
    int size = 16;
    int actualSize = cavity.irreducible_size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityCiTest_area tests GePol cavity surface area for a point charge in Ci symmetry
 */
BOOST_FIXTURE_TEST_CASE(area, GePolCavityCiTest)
{
    double area = 4.0 * M_PI * pow(1.0, 2);
    double actualArea = cavity.elementArea().sum();
    BOOST_REQUIRE_CLOSE(area, actualArea, 1.0e-12);
}

/*! \class GePolCavity
 *  \test \b GePolCavityCiTest_volume tests GePol cavity volume for a point charge in Ci symmetry
 */
BOOST_FIXTURE_TEST_CASE(volume, GePolCavityCiTest)
{
    double volume = 4.0 * M_PI * pow(1.0, 3) / 3.0;
    Eigen::Matrix3Xd elementCenter = cavity.elementCenter();
    Eigen::Matrix3Xd elementNormal = cavity.elementNormal();
    double actualVolume = 0;
    for ( int i = 0; i < cavity.size(); ++i ) {
        actualVolume += cavity.elementArea(i) * elementCenter.col(i).dot(elementNormal.col(
                            i));
    }
    actualVolume /= 3;
    BOOST_REQUIRE_CLOSE(volume, actualVolume, 1.0e-12);
}

BOOST_AUTO_TEST_SUITE_END()

struct GePolCavityC2hTest {
    GePolCavity cavity;
    GePolCavityC2hTest() { SetUp(); }
    void SetUp() {
        Eigen::Vector3d origin(0.0, 0.0, 0.0);
        std::vector<Sphere> spheres;
        Sphere sph1(origin,  1.0);
        spheres.push_back(sph1);
        double area = 0.4;
        double probeRadius = 0.0;
        double minRadius = 100.0;
        // C2h as generated by Oxy and i
        Symmetry group = buildGroup(2, 4, 7, 0);
        cavity = GePolCavity(spheres, area, probeRadius, minRadius, group);
        fs::rename("PEDRA.OUT", "PEDRA.OUT.c2h");
        fs::rename("cavity.off", "cavity.off.c2h");
    }
};

BOOST_FIXTURE_TEST_SUITE(GePolCavityC2h, GePolCavityC2hTest)

/*! \class GePolCavity
 *  \test \b GePolCavityC2hTest_size tests GePol cavity size for a point charge in C2h symmetry
 */
BOOST_FIXTURE_TEST_CASE(size, GePolCavityC2hTest)
{
    int size = 32;
    int actualSize = cavity.size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityC2hTest_irreducible_size tests GePol cavity irreducible size for a point charge in C2h symmetry
 */
BOOST_FIXTURE_TEST_CASE(irreducible_size, GePolCavityC2hTest)
{
    int size = 8;
    int actualSize = cavity.irreducible_size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityC2hTest_area tests GePol cavity surface area for a point charge in C2h symmetry
 */
BOOST_FIXTURE_TEST_CASE(area, GePolCavityC2hTest)
{
    double area = 4.0 * M_PI * pow(1.0, 2);
    double actualArea = cavity.elementArea().sum();
    BOOST_REQUIRE_CLOSE(area, actualArea, 1.0e-12);
}

/*! \class GePolCavity
 *  \test \b GePolCavityC2hTest_volume tests GePol cavity volume for a point charge in C2h symmetry
 */
BOOST_FIXTURE_TEST_CASE(volume, GePolCavityC2hTest)
{
    double volume = 4.0 * M_PI * pow(1.0, 3) / 3.0;
    Eigen::Matrix3Xd elementCenter = cavity.elementCenter();
    Eigen::Matrix3Xd elementNormal = cavity.elementNormal();
    double actualVolume = 0;
    for ( int i = 0; i < cavity.size(); ++i ) {
        actualVolume += cavity.elementArea(i) * elementCenter.col(i).dot(elementNormal.col(
                            i));
    }
    actualVolume /= 3;
    BOOST_REQUIRE_CLOSE(volume, actualVolume, 1.0e-12);
}

BOOST_AUTO_TEST_SUITE_END()

struct GePolCavityD2Test {
    GePolCavity cavity;
    GePolCavityD2Test() { SetUp(); }
    void SetUp() {
        Eigen::Vector3d origin(0.0, 0.0, 0.0);
        std::vector<Sphere> spheres;
        Sphere sph1(origin,  1.0);
        spheres.push_back(sph1);
        double area = 0.4;
        double probeRadius = 0.0;
        double minRadius = 100.0;
        // D2 as generated by C2z and C2x
        Symmetry group = buildGroup(2, 3, 6, 0);
        cavity = GePolCavity(spheres, area, probeRadius, minRadius, group);
        fs::rename("PEDRA.OUT", "PEDRA.OUT.d2");
        fs::rename("cavity.off", "cavity.off.d2");
    }
};

BOOST_FIXTURE_TEST_SUITE(GePolCavityD2, GePolCavityD2Test)

/*! \class GePolCavity
 *  \test \b GePolCavityD2Test_size tests GePol cavity size for a point charge in D2 symmetry
 */
BOOST_FIXTURE_TEST_CASE(size, GePolCavityD2Test)
{
    int size = 32;
    int actualSize = cavity.size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityD2Test_irreducible_size tests GePol cavity irreducible size for a point charge in D2 symmetry
 */
BOOST_FIXTURE_TEST_CASE(irreducible_size, GePolCavityD2Test)
{
    int size = 8;
    int actualSize = cavity.irreducible_size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityD2Test_area tests GePol cavity surface area for a point charge in D2 symmetry
 */
BOOST_FIXTURE_TEST_CASE(area, GePolCavityD2Test)
{
    double area = 4.0 * M_PI * pow(1.0, 2);
    double actualArea = cavity.elementArea().sum();
    BOOST_REQUIRE_CLOSE(area, actualArea, 1.0e-12);
}

/*! \class GePolCavity
 *  \test \b GePolCavityD2Test_volume tests GePol cavity volume for a point charge in D2 symmetry
 */
BOOST_FIXTURE_TEST_CASE(volume, GePolCavityD2Test)
{
    double volume = 4.0 * M_PI * pow(1.0, 3) / 3.0;
    Eigen::Matrix3Xd elementCenter = cavity.elementCenter();
    Eigen::Matrix3Xd elementNormal = cavity.elementNormal();
    double actualVolume = 0;
    for ( int i = 0; i < cavity.size(); ++i ) {
        actualVolume += cavity.elementArea(i) * elementCenter.col(i).dot(elementNormal.col(
                            i));
    }
    actualVolume /= 3;
    BOOST_REQUIRE_CLOSE(volume, actualVolume, 1.0e-12);
}

BOOST_AUTO_TEST_SUITE_END()

struct GePolCavityC2vTest {
    GePolCavity cavity;
    GePolCavityC2vTest() { SetUp(); }
    void SetUp() {
        Eigen::Vector3d origin(0.0, 0.0, 0.0);
        std::vector<Sphere> spheres;
        Sphere sph1(origin,  1.0);
        spheres.push_back(sph1);
        double area = 0.4;
        double probeRadius = 0.0;
        double minRadius = 100.0;
        // C2v as generated by Oyz and Oxz
        Symmetry group = buildGroup(2, 1, 2, 0);
        cavity = GePolCavity(spheres, area, probeRadius, minRadius, group);
        fs::rename("PEDRA.OUT", "PEDRA.OUT.c2v");
        fs::rename("cavity.off", "cavity.off.c2v");
    }
};

BOOST_FIXTURE_TEST_SUITE(GePolCavityC2v, GePolCavityC2vTest)

/*! \class GePolCavity
 *  \test \b GePolCavityC2vTest_size tests GePol cavity size for a point charge in C2v symmetry
 */
BOOST_FIXTURE_TEST_CASE(size, GePolCavityC2vTest)
{
    int size = 32;
    int actualSize = cavity.size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityC2vTest_irreducible_size tests GePol cavity irreducible size for a point charge in C2v symmetry
 */
BOOST_FIXTURE_TEST_CASE(irreducible_size, GePolCavityC2vTest)
{
    int size = 8;
    int actualSize = cavity.irreducible_size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityC2vTest_area tests GePol cavity surface area for a point charge in C2v symmetry
 */
BOOST_FIXTURE_TEST_CASE(area, GePolCavityC2vTest)
{
    double area = 4.0 * M_PI * pow(1.0, 2);
    double actualArea = cavity.elementArea().sum();
    BOOST_REQUIRE_CLOSE(area, actualArea, 1.0e-12);
}

/*! \class GePolCavity
 *  \test \b GePolCavityC2vTest_volume tests GePol cavity volume for a point charge in C2v symmetry
 */
BOOST_FIXTURE_TEST_CASE(volume, GePolCavityC2vTest)
{
    double volume = 4.0 * M_PI * pow(1.0, 3) / 3.0;
    Eigen::Matrix3Xd elementCenter = cavity.elementCenter();
    Eigen::Matrix3Xd elementNormal = cavity.elementNormal();
    double actualVolume = 0;
    for ( int i = 0; i < cavity.size(); ++i ) {
        actualVolume += cavity.elementArea(i) * elementCenter.col(i).dot(elementNormal.col(
                            i));
    }
    actualVolume /= 3;
    BOOST_REQUIRE_CLOSE(volume, actualVolume, 1.0e-12);
}

BOOST_AUTO_TEST_SUITE_END()

struct GePolCavityD2hTest {
    GePolCavity cavity;
    GePolCavityD2hTest() { SetUp(); }
    void SetUp() {
        Eigen::Vector3d origin(0.0, 0.0, 0.0);
        std::vector<Sphere> spheres;
        Sphere sph1(origin,  1.0);
        spheres.push_back(sph1);
        double area = 0.4;
        double probeRadius = 0.0;
        double minRadius = 100.0;
        // D2h as generated by Oxy, Oxz and Oyz
        Symmetry group = buildGroup(3, 4, 2, 1);
        cavity = GePolCavity(spheres, area, probeRadius, minRadius, group);
        fs::rename("PEDRA.OUT", "PEDRA.OUT.d2h");
        fs::rename("cavity.off", "cavity.off.d2h");
    }
};

BOOST_FIXTURE_TEST_SUITE(GePolCavityD2h, GePolCavityD2hTest)

/*! \class GePolCavity
 *  \test \b GePolCavityD2hTest_size tests GePol cavity size for a point charge in D2h symmetry
 */
BOOST_FIXTURE_TEST_CASE(size, GePolCavityD2hTest)
{
    int size = 32;
    int actualSize = cavity.size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityD2hTest_irreducible_size tests GePol cavity irreducible size for a point charge in D2h symmetry
 */
BOOST_FIXTURE_TEST_CASE(irreducible_size, GePolCavityD2hTest)
{
    int size = 4;
    int actualSize = cavity.irreducible_size();
    BOOST_REQUIRE_EQUAL(size, actualSize);
}

/*! \class GePolCavity
 *  \test \b GePolCavityD2hTest_area tests GePol cavity surface area for a point charge in D2h symmetry
 */
BOOST_FIXTURE_TEST_CASE(area, GePolCavityD2hTest)
{
    double area = 4.0 * M_PI * pow(1.0, 2);
    double actualArea = cavity.elementArea().sum();
    BOOST_REQUIRE_CLOSE(area, actualArea, 1.0e-12);
}

/*! \class GePolCavity
 *  \test \b GePolCavityD2hTest_volume tests GePol cavity volume for a point charge in D2h symmetry
 */
BOOST_FIXTURE_TEST_CASE(volume, GePolCavityD2hTest)
{
    double volume = 4.0 * M_PI * pow(1.0, 3) / 3.0;
    Eigen::Matrix3Xd elementCenter = cavity.elementCenter();
    Eigen::Matrix3Xd elementNormal = cavity.elementNormal();
    double actualVolume = 0;
    for ( int i = 0; i < cavity.size(); ++i ) {
        actualVolume += cavity.elementArea(i) * elementCenter.col(i).dot(elementNormal.col(
                            i));
    }
    actualVolume /= 3;
    BOOST_REQUIRE_CLOSE(volume, actualVolume, 1.0e-12);
}

BOOST_AUTO_TEST_SUITE_END()
