name: Build and test PCMSolver

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
  release:
    types:
      - created

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        static: ["--static", ""]
        python-version: 
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
    - uses: actions/checkout@v3

    - name: Cache conda
      uses: actions/cache@v3
      env:
        CACHE_NUMBER: 0  # Increase this value to reset cache if .github/pcmsolver-gha.yml has not changed
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/pcmsolver-gha.yml') }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: pcmsolver-gha
          environment-file: .github/pcmsolver-gha.yml
          channel-priority: true
          python-version: ${{ matrix.python-version }}

    - name: Configure
      shell: bash -l {0}
      run: |
        python ./setup.py --type=$BUILD_TYPE ${{ matrix.static }} --generator=Ninja --prefix=$GITHUB_WORKSPACE/Software/PCMSolver build
        
    - name: Build
      shell: bash -l {0}
      run: |
        cmake --build build --config $BUILD_TYPE --target install -- -v -d stats
        
    - name: Test
      shell: bash -l {0}
      run: |
        cd build
        # exclude green_spherical_diffuse test
        ctest -C $BUILD_TYPE -E green_spherical_diffuse --output-on-failure --verbose
        # run green_spherical_diffuse test
        ./bin/unit_tests "[green_spherical_diffuse]" --success
